"""
X System — Agency HQ Brief Generator
Add this to your brand_os/ folder.
Call render_agency_hq_button() in app.py after render_client_report()
"""

import streamlit as st


def generate_agency_brief(
    brand_name,
    client_inputs,
    brand_data,
    seo_data,
    scores,
    diagnosis_result,
    arc,
    qualification_result,
    lifecycle_stage=None,
    monthly_budget=None,
    client_goal=None,
):
    """Generate a formatted brief that all 6 Agency HQ employees can work from."""

    # Pull key data
    mode          = diagnosis_result.get("primary_mode", "Stabilize")
    priority      = diagnosis_result.get("strategic_priority", "—")
    risk          = diagnosis_result.get("risk_level", "Medium")
    actions       = diagnosis_result.get("immediate_actions", [])
    reasoning     = diagnosis_result.get("reasoning", "")

    value_prop    = brand_data.get("value_proposition", "—")
    target        = brand_data.get("target_audience", "—")
    tone          = brand_data.get("tone", "—")
    weaknesses    = brand_data.get("weaknesses", [])
    diag_summary  = brand_data.get("diagnostic_summary", "")

    seo_score     = seo_data.get("seo_health_score", "—")
    seo_issues    = seo_data.get("seo_weaknesses", [])
    kw_alignment  = seo_data.get("keyword_alignment", "—")

    q_score       = qualification_result.get("qualification_score", "—")
    q_status      = qualification_result.get("qualification_status", "—")
    q_model       = qualification_result.get("engagement_model", "—")

    # Score summary
    score_lines = []
    for pillar, data in scores.items():
        s = data.get("score", "—")
        label = pillar.replace("_", " ").title()
        score_lines.append(f"  • {label}: {s}/100")

    # Strategy summary
    strategy_lines = []
    if arc and isinstance(arc, list) and len(arc) > 0:
        for i, month in enumerate(arc):
            if isinstance(month, dict):
                phase = month.get("phase") or month.get("objective") or f"Phase {i+1}"
                focus = month.get("focus", [])
                focus_str = ", ".join(focus) if isinstance(focus, list) else str(focus)
                strategy_lines.append(f"  Month {month.get('month', i+1)}: {phase} — {focus_str}")
    else:
        strategy_lines = [
            f"  Month 1: Foundation — {mode}. Fix positioning, messaging, content baseline.",
            f"  Month 2: Build — {priority}. Content calendar, SEO push, lead magnet.",
            f"  Month 3: Scale — Conversion Push. Retargeting, case studies, performance review.",
        ]

    actions_str = "\n".join([f"  {i+1}. {a}" for i, a in enumerate(actions)]) if actions else "  — See diagnosis"
    weaknesses_str = "\n".join([f"  • {w}" for w in weaknesses]) if weaknesses else "  — None identified"
    seo_issues_str = "\n".join([f"  • {w}" for w in seo_issues]) if seo_issues else "  — None identified"
    score_str = "\n".join(score_lines) if score_lines else "  — Not available"
    strategy_str = "\n".join(strategy_lines)

    brief = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏢 AGENCY HQ — CLIENT BRIEF
Generated by X System · ArkX Intelligence
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📌 CLIENT OVERVIEW
Brand: {brand_name}
Goal: {client_goal or "—"}
Budget: ₹{int(monthly_budget):,}/month
Stage: {lifecycle_stage or "—"}
Service: {client_inputs.get("Service", "—")}
Location: {client_inputs.get("Location", "—")}
Current Problem: {client_inputs.get("Current Problem", "—")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🧠 BRAND INTELLIGENCE
Value Proposition: {value_prop}
Target Audience: {target}
Brand Tone: {tone}
Diagnostic Summary: {diag_summary}

Brand Weaknesses:
{weaknesses_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 PILLAR SCORES
{score_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔍 SEO INTELLIGENCE
SEO Health Score: {seo_score}/100
Keyword Alignment: {kw_alignment}

SEO Issues to Fix:
{seo_issues_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚡ DIAGNOSIS
Strategic Mode: {mode}
Strategic Priority: {priority}
Risk Level: {risk}

Reasoning: {reasoning}

Immediate Actions:
{actions_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 CLIENT QUALIFICATION
Score: {q_score}/100
Status: {q_status}
Engagement Model: {q_model}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📅 90-DAY STRATEGY
{strategy_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🤝 INSTRUCTIONS FOR ALL EMPLOYEES

Maya (Social Media): Build a 90-day Instagram & LinkedIn content plan based on the strategy above. Focus on the brand's tone ({tone}) and target audience ({target}). Budget for paid social is within ₹{int(monthly_budget):,}/month total.

Daniel (SEO): Fix the SEO issues listed above. Start with keyword alignment improvements and structured content. Priority keyword focus area: {client_inputs.get("Service", "the core service")}.

Priya (Paid Media): Plan a paid campaign within ₹{int(monthly_budget):,}/month. Focus on {client_goal or "brand awareness"} for {target}. Start with test budgets before scaling.

Marcus (Brand Designer): Create visual assets aligned to the brand tone ({tone}). Priority: fix any positioning gaps in visual identity. Design creatives for Month 1 content.

Sophie (Account Manager): Set up the 90-day project timeline. Schedule monthly reviews. Onboard client with the engagement model: {q_model}.

Alex (Business Development): Note this client's qualification score is {q_score}/100 with status: {q_status}. Identify upsell opportunities after Month 1. Engagement model: {q_model}.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""".strip()

    return brief


def render_agency_hq_button(
    brand_name,
    client_inputs,
    brand_data,
    seo_data,
    scores,
    diagnosis_result,
    arc,
    qualification_result,
    lifecycle_stage=None,
    monthly_budget=None,
    client_goal=None,
):
    """Render the Send to Agency HQ section in Streamlit."""

    st.markdown("""
    <div style="
        margin: 40px 0 20px;
        padding: 28px 32px;
        background: #0d1017;
        border: 1px solid #1a1f2e;
        border-radius: 14px;
        border-left: 4px solid #c8ff00;
        position: relative;
    ">
        <div style="font-family:'Syne',sans-serif; font-size:10px; font-weight:700;
                    letter-spacing:0.15em; text-transform:uppercase; color:#6b7280; margin-bottom:6px">
            Next Step
        </div>
        <div style="font-family:'Syne',sans-serif; font-size:20px; font-weight:800;
                    color:#e8eaf0; margin-bottom:8px">
            Send to Agency HQ
        </div>
        <div style="font-size:13px; color:#6b7280; line-height:1.6">
            Generate a complete brief for all 6 employees — Maya, Daniel, Priya, Marcus, Sophie & Alex.<br>
            Copy it and paste into the <strong style="color:#c8ff00">Client Context</strong> bar in Agency HQ.
            All employees will instantly know exactly what to do for the next 90 days.
        </div>
    </div>
    """, unsafe_allow_html=True)

    if st.button("📋  Generate Agency HQ Brief", use_container_width=True):
        brief = generate_agency_brief(
            brand_name=brand_name,
            client_inputs=client_inputs,
            brand_data=brand_data,
            seo_data=seo_data,
            scores=scores,
            diagnosis_result=diagnosis_result,
            arc=arc,
            qualification_result=qualification_result,
            lifecycle_stage=lifecycle_stage,
            monthly_budget=monthly_budget,
            client_goal=client_goal,
        )
        st.session_state["agency_brief"] = brief

    if st.session_state.get("agency_brief"):
        brief = st.session_state["agency_brief"]

        st.markdown("""
        <div style="font-family:'Syne',sans-serif; font-size:10px; font-weight:700;
                    letter-spacing:0.15em; text-transform:uppercase; color:#c8ff00;
                    margin: 16px 0 8px">
            ✅ Brief Ready — Copy everything below
        </div>
        """, unsafe_allow_html=True)

        st.code(brief, language=None)

        st.markdown("""
        <div style="font-size:12px; color:#6b7280; margin-top:8px; line-height:1.7">
            👆 Click the copy icon (top right of the box above) → Open Agency HQ →
            Paste into the <strong style="color:#e8eaf0">Client Context</strong> bar at the top → All 6 employees are now briefed.
        </div>
        """, unsafe_allow_html=True)